/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import javax.swing.JOptionPane;

/**
 *
 * @author Aluno
 */
public class MinhaPrimeiraTelinha extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MinhaPrimeiraTelinha.class.getName());

    /**
     * Creates new form MinhaPrimeiraTelinha
     */
    public MinhaPrimeiraTelinha() {
        initComponents();
        
        JOptionPane.showMessageDialog(null, "hello world");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jtextfieldnome = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jtextfieldendereco = new javax.swing.JLabel();
        jtextfieldsalvar = new javax.swing.JButton();
        JButtonPreencherAutomatico = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.addActionListener(this::jTextField1ActionPerformed);

        jtextfieldnome.setText("nome ");

        jTextField2.addActionListener(this::jTextField2ActionPerformed);

        jtextfieldendereco.setText("endereço");

        jtextfieldsalvar.setText("salvar");
        jtextfieldsalvar.addActionListener(this::jtextfieldsalvarActionPerformed);

        JButtonPreencherAutomatico.setText("prencher automatico");
        JButtonPreencherAutomatico.addActionListener(this::JButtonPreencherAutomaticoActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField1)
            .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtextfieldnome)
                    .addComponent(jtextfieldendereco)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtextfieldsalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JButtonPreencherAutomatico)))
                .addGap(0, 173, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jtextfieldnome, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jtextfieldendereco)
                .addGap(18, 18, 18)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtextfieldsalvar)
                    .addComponent(JButtonPreencherAutomatico)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jtextfieldsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextfieldsalvarActionPerformed
        JOptionPane.showMessageDialog(null, "O botão salvar foi clicado");
        jtextfieldnome.setText("Gustavo caires");
        
      
    }//GEN-LAST:event_jtextfieldsalvarActionPerformed

    private void JButtonPreencherAutomaticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonPreencherAutomaticoActionPerformed
        
    }//GEN-LAST:event_JButtonPreencherAutomaticoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MinhaPrimeiraTelinha().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtonPreencherAutomatico;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel jtextfieldendereco;
    private javax.swing.JLabel jtextfieldnome;
    private javax.swing.JButton jtextfieldsalvar;
    // End of variables declaration//GEN-END:variables
}
